---
title: C6255
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6255
helpviewer_keywords:
- C6255
ms.assetid: bb6430b2-782a-4410-a8e1-609df06007de
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: bd09eed020e02e0b17828e0746c9413488ae8618
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 10/07/2019
ms.locfileid: "72013499"
---
# <a name="c6255"></a>C6255
AVERTISSEMENT C6255 : _ alloca indique un échec en déclenchant une exception de dépassement de capacité de la pile. Envisagez d’utiliser _malloca à la place

 Cet avertissement indique qu’un appel à `_alloca` a été détecté en dehors de la gestion des exceptions locales. `_alloca` doit toujours être appelé à partir de la plage protégée d’un gestionnaire d’exceptions, car il peut déclencher une exception de dépassement de capacité de la pile en cas d’échec. Si possible, au lieu d’utiliser `_alloca`, envisagez d’utiliser `_malloca`, qui est une version plus sécurisée de `_alloca`.

## <a name="example"></a>Exemple
 Le code suivant génère cet avertissement, car `_alloca` peut générer une exception :

```
#include <windows.h>

void f( )
{
  void *p = _alloca(10);
  // code ...
}
```

 Pour corriger cet avertissement, utilisez `_malloca` et ajoutez un gestionnaire d’exceptions comme indiqué dans le code suivant :

```
#include <windows.h>
#include <malloc.h>

void f( )
{
  void *p;
  int errcode;
  __try
  {
    p = _malloca(10);
    // code...
    _freea(p);
  }
  __except( (GetExceptionCode() == STATUS_STACK_OVERFLOW ) ?
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    errcode = _resetstkoflw();
    // code ...
  }
}
```

## <a name="see-also"></a>Voir aussi
 [_malloca](/cpp/c-runtime-library/reference/malloca)