---
title: C6255
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6255
helpviewer_keywords:
- C6255
ms.assetid: bb6430b2-782a-4410-a8e1-609df06007de
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: ca09619a9a7258d24f9f60ad8d6fa27553123709
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878565"
---
# <a name="c6255"></a>C6255
Avertissement C6255 : _alloca signale un échec en levant une exception de dépassement de capacité de la pile. Envisagez plutôt d’utiliser _malloca

 Cet avertissement indique qu’un appel à `_alloca` a été détecté en dehors de la gestion des exceptions locales. `_alloca` doit toujours être appelé à partir de la plage protégée d’un gestionnaire d’exceptions, car il peut déclencher une exception de dépassement de capacité de la pile en cas d’échec. Si possible, au lieu d’utiliser `_alloca`, envisagez d’utiliser `_malloca` qui est une version plus sécurisée de `_alloca`.

## <a name="example"></a>Exemple
 Le code suivant génère cet avertissement, car `_alloca` peut générer une exception :

```cpp
#include <windows.h>

void f( )
{
  void *p = _alloca(10);
  // code ...
}
```

 Pour corriger cet avertissement, utilisez `_malloca` et ajoutez un gestionnaire d’exceptions comme indiqué dans le code suivant :

```cpp
#include <windows.h>
#include <malloc.h>

void f( )
{
  void *p;
  int errcode;
  __try
  {
    p = _malloca(10);
    // code...
    _freea(p);
  }
  __except( (GetExceptionCode() == STATUS_STACK_OVERFLOW ) ?
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    errcode = _resetstkoflw();
    // code ...
  }
}
```

## <a name="see-also"></a>Voir aussi
 [_malloca](/cpp/c-runtime-library/reference/malloca)
