---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 683619442865a231742fdecba9e94a893d103144
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 02/15/2020
ms.locfileid: "77267031"
---
# <a name="c6318"></a>C6318
avertissement C6318 : __try/\__except mal défini : utilisation de la constante EXCEPTION_CONTINUE_SEARCH ou d’une autre constante qui prend la valeur zéro dans l’expression de filtre d’exception. Le code du bloc de gestionnaire d’exceptions n’est pas exécuté

 Cet avertissement indique que si une exception se produit dans le bloc protégé de ce gestionnaire d’exceptions structurées, l’exception n’est pas gérée, car la constante `EXCECPTION_CONTINUE_SEARCH` est utilisée dans l’expression de filtre d’exception.

 Ce code est équivalent au bloc protégé sans le bloc de gestionnaire d’exceptions, car le bloc de gestionnaire n’est pas exécuté.

## <a name="example"></a>Exemple
 Le code suivant génère cet avertissement :

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Pour corriger cet avertissement, utilisez le code suivant :

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Voir aussi
 [try-except, instruction](/cpp/cpp/try-except-statement)
